version: 2.1
orbs:
  codecov: codecov/codecov@1.2.3
jobs:
  build_and_test:
    docker:
      - image: maven:3.6.0-jdk-8
    steps:
      - checkout
      - run:
          name: Maven unit tests and make package
          command: mvn clean clover:setup package
      - run:
          name: Generate code coverage report
          command: mvn clover:clover
      - codecov/upload
workflows:
  all:
    jobs:
      - build_and_test
